server:
  port: 8080
  contextPath: /
 
datasource:
  fujifilm:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 3
    minimumIdle: 1
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTimeout: 30000
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

resources:
  static-locations: classpath:/resources/