server:
  port: 80
  contextPath: /
 
datasource:
  fujifilm:
    url:  https://postgresql-cubed-63195.herokuapp.com/
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 3
    minimumIdle: 1
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTimeout: 30000
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

resources:
  static-locations: classpath:/resources/